### ISSUE TITLE
Don't select the channel we're announcing to

### ISSUE THREAD

**Issue by br0xen** [devict/herald#1]
Would this be best accomplished by passing the DestChan config value to the selectChannel function? Or would it be worth it to pass a slice of channel names that we don't want to include and throw the DestChan into that?

**Comment by br0xen** [comment]
Or should we just have an `if c.Name == cnf.DestChan, then reselect` in the main function?

**Comment by jcbwlkr** [comment]
I like your second idea but slightly modified

```
func selectChannel(coll *mgo.Collection, api *slack.Client, ignore Channels) (slack.Channel, error) {
```

We have a type `Channels` which is a `[]Channel`. It has a method `Contains` which is handy.
